"""The vocabulary gate: the retired words stay retired.

`CONTEXT.md` retired two words. "Bundle" was the name for a container we
invented to hold shipped content, and that container is the workbook itself
now. `logical_id` said what the field is not, where `standard_id` states the
rule: only standard content has one.

A merge or a new call site can bring a retired word back. This test reads the
source files and needs no database. It reports the file and the line of every
offence.
"""

import os
import re
import unittest

import frappe

# The word is retired for the shipping unit, not for every meaning. A JavaScript
# asset bundle is Frappe's word and stays. Each exemption lists the literal text
# that excuses a line.
#
# Keep it literal. A pattern permissive enough to admit `*.bundle.js` also admits
# a sync module that ships one, and that module is what the gate guards.
EXEMPTIONS = {
    # a JavaScript asset bundle — Frappe's word, not ours
    "insights/hooks.py": ["insights_nudge.bundle.js"],
    "frontend/src2/query/helpers.ts": ["into the island bundle"],
    "frontend/src2/helpers/navigation.ts": ["drags every routed page into the bundle"],
    "frontend/src2/controllers.ts": ["would bundle socket.io-client"],
    # a CA bundle — the TLS term, nothing to do with shipping analytics
    "insights/http.py": ["its CA bundle and its netrc"],
    "insights/tests/test_data_source_ssl.py": ['ssl={"ca": <bundle>} alone'],
    "docs/adr/outbound-http-to-user-chosen-urls.md": [
        "`REQUESTS_CA_BUNDLE`",
        "operator's CA bundle from the environment",
    ],
}

# Directories under the scanned roots that are not source.
SKIPPED = (
    "insights/public",  # build output, and the nudge asset itself
    "insights/locale",  # generated; regenerated by its own chore commit
    "__pycache__",
    "node_modules",
)

SCANNED_SUFFIXES = (".py", ".ts", ".vue", ".json", ".txt", ".js", ".md")

# The two code trees, plus the docs that outlive a branch. Two exclusions, both
# deliberate. `docs/projects/` holds branch-scoped build logs, deleted when the
# branch merges, and a dated record may say what a word used to be. `CONTEXT.md`
# is the glossary this gate enforces — it retires a word by naming it under
# `_Avoid_`, the same reason this file excludes itself.
SCANNED_ROOTS = (
    "insights",
    "frontend/src2",
    "docs/adr",
    "docs/agents",
    "AGENTS.md",
)

# the gate has to name what it forbids
GATE = "insights/tests/test_vocabulary.py"

RETIRED = re.compile(r"bundle|logical_id", re.IGNORECASE)


def app_root() -> str:
    return os.path.dirname(frappe.get_app_path("insights"))


def source_files():
    for root in SCANNED_ROOTS:
        target = os.path.join(app_root(), root)
        if os.path.isfile(target):
            yield root, target
            continue
        for dirpath, dirnames, filenames in os.walk(target):
            relative_dir = os.path.relpath(dirpath, app_root())
            if any(part in relative_dir for part in SKIPPED):
                dirnames[:] = []
                continue
            for filename in sorted(filenames):
                if not filename.endswith(SCANNED_SUFFIXES):
                    continue
                path = os.path.join(dirpath, filename)
                relative_path = os.path.relpath(path, app_root())
                if relative_path == GATE:
                    continue
                yield relative_path, path


def offences():
    """Every line carrying a retired word that no exemption covers."""
    found = []
    for relative_path, path in source_files():
        allowed = EXEMPTIONS.get(relative_path, [])
        try:
            with open(path, encoding="utf-8") as f:
                lines = f.readlines()
        except UnicodeDecodeError:
            continue
        for number, line in enumerate(lines, start=1):
            if RETIRED.search(line) and not any(reason in line for reason in allowed):
                found.append(f"{relative_path}:{number}: {line.strip()}")
    return found


class TestRetiredVocabulary(unittest.TestCase):
    def test_no_source_file_speaks_the_retired_vocabulary(self):
        found = offences()
        self.assertEqual(
            found,
            [],
            "These lines use a retired word. The shipping unit is a workbook and "
            "the identity field is `standard_id`. If a line means a JavaScript "
            "asset bundle, add it to EXEMPTIONS with its reason:\n  " + "\n  ".join(found),
        )

    def test_every_exemption_is_still_earning_its_place(self):
        """An exemption that outlives the line it excused becomes a hole.

        The list is small and hand-written. This test asserts that each entry
        still matches a line, so a dead entry gets removed.
        """
        stale = []
        for relative_path, reasons in EXEMPTIONS.items():
            path = os.path.join(app_root(), relative_path)
            if not os.path.isfile(path):
                stale.append(f"{relative_path} (file is gone)")
                continue
            with open(path, encoding="utf-8") as f:
                content = f.read()
            for reason in reasons:
                if reason not in content:
                    stale.append(f"{relative_path}: {reason!r}")

        self.assertEqual(stale, [], f"EXEMPTIONS entries that match nothing any more: {stale}")
